import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Button } from 'ui'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Vercel from '../public/vercel.svg'

const Home: NextPage = () => {
  const { t } = useTranslation()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3>Next app 1</h3>
        <Button label="Hello team" />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Vercel />
          </span>
        </a>
        <div>{t('Email')}</div>
      </footer>
    </div>
  )
}

export default Home
export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  }
}
