module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'next',
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:import/typescript',
    'prettier',
  ],
  settings: {
    next: {
      rootDir: ['apps/*/', 'packages/*/'],
    },
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
        project: ['apps/*/tsconfig.json'],
      },
    },
  },
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: ['react', '@typescript-eslint', 'prettier'],
  rules: {
    'react/prop-types': 'off',
    '@typescript-eslint/ban-ts-comment': 0,
    '@typescript-eslint/no-non-null-assertion': 0,
    'cypress/no-unnecessary-waiting': 0,
    'no-console': 'error',
    'no-alert': 'error',
    '@typescript-eslint/no-explicit-any': 0,
    'react/display-name': 0,
    'react-hooks/exhaustive-deps': 0,
    'sort-imports': 'off',
    'prettier/prettier': 'error',
    'import/first': 'error',
    'import/no-duplicates': 'error',
    'react/jsx-no-target-blank': 0,
    'no-unused-vars': 'error',
    'no-useless-return': 'error',
    'no-return-await': 'error',
    'no-else-return': 'error',
    '@typescript-eslint/no-var-requires': 0,
    'no-async-promise-executor': 0,
    'import/no-named-as-default': 0,
    '@typescript-eslint/explicit-module-boundary-types': 0,
    'react/jsx-uses-react': 0,
    'react/react-in-jsx-scope': 0,
  },
};
